### PR TITLE
Closes #31 Added logic to call getTopic

### LINKED ISSUE #31: Topic change is not displayed in Slack
When we start the hangout and change the topic that name is not passed to Slack.

Instead of using:
startData.title

As the title we should use
gapi.hangout.getTopic()

### PR DESCRIPTION
**Pull request by joaopapereira**
fixes #31

### CODE REVIEW

**Comment by tansaku** [comment]
great stuff @joaopapereira - I assume this it all passing locally - we so need to get CI set up on this repo!

**Comment by joaopapereira** [comment]
I run all the tests locally and they are all green.
The only thing I was not able to test is the App itself in Hangouts.

**Comment by tansaku** [comment]
thanks @joaopapereira - I believe we can run tests using the staging server - i'll have to take a run up to work out how to do that again :-) @diraulo might remember :-)

**Comment by tansaku** [comment]
yeah and all green for me locally

**Comment by tansaku** [comment]
@joaopapereira could you re-open this against develop?  It's looks good to go to me - but maybe better to get it on develop and then test against AV staging there

**Comment by joaopapereira** [comment]
@tansaku change the PR to development

**Comment by tansaku** [comment]
thanks @joaopapereira

**Comment by tansaku** [comment]
@mtc2013 this is looking good to me - care to take a gander?

**Comment by mtc2013** [comment]
@tansaku @joaopapereira this looks good to me.

**Pull request merged**
